site_name: MnMS
site_url: ""
use_directory_urls: false
site_description: 'MnMS'' documentation'
nav:
  - Home: index.md
  - Installation: installation.md
  - Tutorial:
      - Quick start: QuickStartTutorial.ipynb
  - Code Reference:
      - mnms: reference/SUMMARY.md

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/EMob-Lab/mnms

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      watch:
        - src/mnms
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      include_source: true
